sclubs/clubs/urls.py
__author__ = 'Evgeniy Tatarintsev'
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
from .views import (ClubDetailView,
                    ClubsIndexView,
                    ClubsBySportView,
                    ClubCoachesView,
                    CreateClubView)

urlpatterns = patterns('',
    url(r'^$', ClubsIndexView.as_view(), name='index'),
    url(r'^create/$', login_required(CreateClubView.as_view()), name='create'),
    #url(r'^category/(?P<slug>[-a-zA-Z0-9_]+)/$', CategoryDetailView.as_view(), name='category'),
    url(r'^sport/(?P<slug>[-a-zA-Z0-9_]+)/$', ClubsBySportView.as_view(), name='sport'),
    url(r'^(?P<slug>[-a-zA-Z0-9_]+)/$', ClubDetailView.as_view(), name='detail'),
    url(r'^(?P<slug>[-a-zA-Z0-9_]+)/coaches/$', ClubCoachesView.as_view(), name='coaches'),
)

sclubs/news/urls.py
__author__ = 'Evgeniy Tatarintsev'
from django.conf.urls import patterns, url

from .views import EntryListView, EntryDetail

urlpatterns = patterns('',
    url(r'^$', EntryListView.as_view(), name='index'),
    url(r'^(?P<slug>[-a-zA-Z0-9_]+)/$', EntryDetail.as_view(), name='detail'),
)

sclubs/urls.py
__author__ = 'Evgeniy Tatarintsev'
from django.conf.urls import patterns, url, include
from django.contrib import admin
from django.conf import settings

from sclubs.generic.views import HomePageView

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^ckeditor/', include('ckeditor.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^hit/update/$', 'hitcount.views.update_hit_count_ajax',
                                            name='hitcount_update_ajax'),

    url(r'^$', HomePageView.as_view(), name='home-page'),
    url(r'^news/', include('sclubs.news.urls', namespace='news')),
    url(r'^articles/', include('sclubs.articles.urls', namespace='articles')),
    url(r'^clubs/', include('sclubs.clubs.urls', namespace='clubs')),
    url(r'^accounts/', include('sclubs.accounts.urls', namespace='accounts')),

)


if settings.DEBUG:
    urlpatterns += patterns("",
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
            'show_indexes': True}),
    )

sclubs/utils/urls.py
__author__ = 'Evgeniy Tatarintsev'
import re
import unicodedata

from django.core.exceptions import ObjectDoesNotExist
from django.core.urlresolvers import (resolve, reverse, NoReverseMatch,
                                      get_script_prefix)
from django.shortcuts import redirect
from django.utils.encoding import smart_unicode
from django.utils import translation

from sclubs import settings
from sclubs.utils.importing import import_dotted_path


def admin_url(model, url, object_id=None):
    """
    Returns the URL for the given model and admin url name.
    """
    opts = model._meta
    url = "admin:%s_%s_%s" % (opts.app_label, opts.object_name.lower(), url)
    args = ()
    if object_id is not None:
        args = (object_id,)
    return reverse(url, args=args)


def home_slug():
    """
    Returns the slug arg defined for the ``home`` urlpattern, which
    is the definitive source of the ``url`` field defined for an
    editable homepage object.
    """
    prefix = get_script_prefix()
    slug = reverse("home")
    if slug.startswith(prefix):
        slug = '/' + slug[len(prefix):]
    try:
        return resolve(slug).kwargs["slug"]
    except KeyError:
        return slug




def unique_slug(queryset, slug_field, slug):
    """
    Ensures a slug is unique for the given queryset, appending
    an integer to its end until the slug is unique.
    """
    i = 0
    while True:
        if i > 0:
            if i > 1:
                slug = slug.rsplit("-", 1)[0]
            slug = "%s-%s" % (slug, i)
        try:
            queryset.get(**{slug_field: slug})
        except ObjectDoesNotExist:
            break
        i += 1
    return slug


def login_redirect(request):
    """
    Returns the redirect response for login/signup. Favors:
    - next param
    - LOGIN_REDIRECT_URL setting
    - homepage
    """
    ignorable_nexts = ("",)
    if "sclubs.accounts" in settings.INSTALLED_APPS:
        from sclubs.accounts import urls
        ignorable_nexts += (urls.SIGNUP_URL, urls.LOGIN_URL, urls.LOGOUT_URL)
    next = request.REQUEST.get("next", "")
    if next in ignorable_nexts:
        try:
            next = reverse(settings.LOGIN_REDIRECT_URL)
        except NoReverseMatch:
            next = "/"
    return redirect(next)


def path_to_slug(path):
    """
    Removes everything from the given URL path, including
    language code and ``PAGES_SLUG`` if any is set, returning
    a slug that would match a ``Page`` instance's slug.
    """
    from mezzanine.urls import PAGES_SLUG
    lang_code = translation.get_language_from_path(path)
    for prefix in (lang_code, settings.SITE_PREFIX, PAGES_SLUG):
        if prefix:
            path = path.replace(prefix, "", 1)
    return path.strip("/") or "/"

sclubs/articles/models.py
__author__ = 'Evgeniy Tatarintsev'
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.core.urlresolvers import reverse
from django.utils.safestring import mark_safe
from sclubs.core.models import Displayable, ImagedContent, RichText, Ownable, DisplayableManager
from sclubs.generic.models import Sport, Gallery, Keyword


class ArticleManager(DisplayableManager):
    def most_popular(self):
        return self.order_by('-views_count')


class Category(Displayable, ImagedContent):
    position = models.PositiveIntegerField(default=0)

    class Meta:
        verbose_name = _('Category')
        verbose_name_plural = _('Categories')
        ordering = ['position', ]

    def get_absolute_url(self):
        return reverse('articles:category', kwargs={'slug': self.slug})


class Article(Displayable, ImagedContent, Ownable):
    categories = models.ManyToManyField(Category, verbose_name=_('Categories'), related_name='articles')
    tags = models.ManyToManyField(Keyword, verbose_name=_('Tags'), related_name='articles', null=True, blank=True)
    sports = models.ManyToManyField(Sport, null=True, blank=True,
                                    verbose_name=_('Sports'), related_name='articles')
    gallery = models.ForeignKey(Gallery, verbose_name=_('Gallery'), null=True, blank=True, related_name='+')
    related_articles = models.ManyToManyField('self', verbose_name=_('Related articles'), null=True, blank=True)

    objects = ArticleManager()

    class Meta:
        verbose_name = _('Article')
        verbose_name_plural = _('Articles')

    def get_absolute_url(self):
        return reverse('articles:detail', kwargs={'slug': self.slug})

    def get_description(self):
        return self.meta_description

    def get_tags(self):
        _tags = []
        a = u'<a href="{url}">{tag.title}</a>'

        for tag in self.tags.all():
            url = reverse('articles:tagged', kwargs={'slug': tag.slug})
            _tags.append(a.format(url=url, tag=tag))

        return mark_safe(u', '.join([_tag for _tag in _tags]))

    def categories_as_tags(self):
        _categories = []
        a = u'<a href="{url}">{tag.title}</a>'

        for cat in self.categories.all():
            _categories.append(a.format(url=cat.get_absolute_url(), tag=cat))
        print self.categories.all()
        return mark_safe(u', '.join([cat for cat in _categories]))

    def get_related(self):
        related = Article.objects.filter(tags__in=self.tags.all())
        related |= self.related_articles.all()
        return related.exclude(pk=self.pk).distinct()


class Aphorism(Displayable, RichText):
    author = models.CharField(_('Author'), max_length=100, null=True, blank=True)

    class Meta:
        verbose_name = _('Aphorism')
        verbose_name_plural = _('Aphorisms')

sclubs/exercises/models.py
__author__ = 'Evgeniy Tatarintsev'

sclubs/seo/models.py
__author__ = 'Evgeniy Tatarintsev'
from django.db import models
from django.utils.translation import ugettext as _


class MetaTags(models.Model):
    name = models.CharField(_('Verbose name'), max_length=250)
    page_url = models.CharField(_('Page URL'), max_length=250, db_index=True)

    title = models.CharField(_('Page title'), max_length=100)
    description = models.TextField(_('Page description'))
    keywords = models.CharField(_('Page keywords'), max_length=100, blank=True, null=True)

    class Meta:
        verbose_name = _('Meta tags')
        verbose_name_plural = _('Meta tags')

    def __unicode__(self):
        return self.name

sclubs/clubs/forms.py
#-*- coding: utf-8 -*-
__author__ = 'Evgeniy Tatarintsev'
from django import forms

from .models import Club


class ClubForm(forms.ModelForm):
    class Meta:
        model = Club
        fields = ('title', 'logo', 'content', 'sports')

sclubs/core/forms.py
__author__ = 'john'
from uuid import uuid4

from django import forms
from django.forms.extras.widgets import SelectDateWidget
from django.utils.safestring import mark_safe
from django.utils.translation import ugettext as _
from django.contrib.staticfiles.storage import staticfiles_storage
from django.conf import settings

from sclubs.core.models import Orderable



class TinyMceWidget(forms.Textarea):
    """
    Setup the JS files and targetting CSS class for a textarea to
    use TinyMCE.
    """

    class Media:
        js = _tinymce_js

    def __init__(self, *args, **kwargs):
        super(TinyMceWidget, self).__init__(*args, **kwargs)
        self.attrs["class"] = "mceEditor"


class OrderWidget(forms.HiddenInput):
    """
    Add up and down arrows for ordering controls next to a hidden
    form field.
    """
    def render(self, *args, **kwargs):
        rendered = super(OrderWidget, self).render(*args, **kwargs)
        arrows = ["<img src='%sadmin/img/admin/arrow-%s.gif' />" %
            (settings.STATIC_URL, arrow) for arrow in ("up", "down")]
        arrows = "<span class='ordering'>%s</span>" % "".join(arrows)
        return rendered + mark_safe(arrows)


class DynamicInlineAdminForm(forms.ModelForm):
    """
    Form for ``DynamicInlineAdmin`` that can be collapsed and sorted
    with drag and drop using ``OrderWidget``.
    """

    class Media:
        js = ("mezzanine/js/jquery-ui-1.9.1.custom.min.js",
              "mezzanine/js/admin/dynamic_inline.js",)

    def __init__(self, *args, **kwargs):
        super(DynamicInlineAdminForm, self).__init__(*args, **kwargs)
        if issubclass(self._meta.model, Orderable):
            self.fields["_order"] = forms.CharField(label=_("Order"),
                widget=OrderWidget, required=False)


class SplitSelectDateTimeWidget(forms.SplitDateTimeWidget):
    """
    Combines Django's ``SelectDateTimeWidget`` and ``SelectDateWidget``.
    """
    def __init__(self, attrs=None, date_format=None, time_format=None):
        date_widget = SelectDateWidget(attrs=attrs)
        time_widget = forms.TimeInput(attrs=attrs, format=time_format)
        forms.MultiWidget.__init__(self, (date_widget, time_widget), attrs)


class CheckboxSelectMultiple(forms.CheckboxSelectMultiple):
    """
    Wraps render with a CSS class for styling.
    """
    def render(self, *args, **kwargs):
        rendered = super(CheckboxSelectMultiple, self).render(*args, **kwargs)
        return mark_safe("<span class='multicheckbox'>%s</span>" % rendered)


def get_edit_form(obj, field_names, data=None, files=None):
    """
    Returns the in-line editing form for editing a single model field.
    """

    # Map these form fields to their types defined in the forms app so
    # we can make use of their custom widgets.
    from mezzanine.forms import fields
    widget_overrides = {
        forms.DateField: fields.DATE,
        forms.DateTimeField: fields.DATE_TIME,
        forms.EmailField: fields.EMAIL,
    }

    class EditForm(forms.ModelForm):
        """
        In-line editing form for editing a single model field.
        """

        app = forms.CharField(widget=forms.HiddenInput)
        model = forms.CharField(widget=forms.HiddenInput)
        id = forms.CharField(widget=forms.HiddenInput)
        fields = forms.CharField(widget=forms.HiddenInput)

        class Meta:
            model = obj.__class__
            fields = field_names.split(",")

        def __init__(self, *args, **kwargs):
            super(EditForm, self).__init__(*args, **kwargs)
            self.uuid = str(uuid4())
            for f in self.fields.keys():
                field_class = self.fields[f].__class__
                try:
                    field_type = widget_overrides[field_class]
                except KeyError:
                    pass
                else:
                    self.fields[f].widget = fields.WIDGETS[field_type]()
                css_class = self.fields[f].widget.attrs.get("class", "")
                css_class += " " + field_class.__name__.lower()
                self.fields[f].widget.attrs["class"] = css_class
                self.fields[f].widget.attrs["id"] = "%s-%s" % (f, self.uuid)
                if settings.FORMS_USE_HTML5 and self.fields[f].required:
                    self.fields[f].widget.attrs["required"] = ""

    initial = {"app": obj._meta.app_label, "id": obj.id,
               "fields": field_names, "model": obj._meta.object_name.lower()}
    return EditForm(instance=obj, initial=initial, data=data, files=files)

sclubs/accounts/views.py
#-*- coding: utf-8 -*-
__author__ = 'Evgeniy Tatarintsev'
from django.views.generic import DetailView

from .models import User


class UserProfileView(DetailView):
    context_object_name = "profile_owner"

    def get_queryset(self):
        return User.objects.active()

    def get_context_data(self, **kwargs):
        ctx = super(UserProfileView, self).get_context_data(**kwargs)
        ctx['can_edit'] = self.request.user == self.object
        return ctx

sclubs/articles/views.py
__author__ = 'Evgeniy Tatarintsev'
from django.utils.timezone import now
from django.views.generic import ListView, DetailView
from django.http import Http404

from models import Article, Aphorism, Category
from sclubs.generic.models import Keyword


class ArticleDetailView(DetailView):
    def get_queryset(self):
        return Article.objects.published()

    def get_object(self, queryset=None):
        article = self.get_queryset().filter(slug=self.kwargs['slug'])
        if not article:
            raise Http404
        article.update(last_view=now())
        return article[0]


class CategoryDetailView(DetailView):
    def get_queryset(self):
        return Category.objects.published()


class CategoryListView(ListView):
    def get_queryset(self):
        return Category.objects.published()


class TaggedArticlesView(DetailView):
    model = Keyword
    template_name = 'articles/tagged_list.html'
    context_object_name = 'tag'

sclubs/clubs/views.py
#-*- coding: utf-8 -*-
__author__ = 'Evgeniy Tatarintsev'
from django.views.generic import DetailView, ListView, CreateView, UpdateView
from django.http import Http404
from django.db.models import Q

from sclubs.generic.models import Sport, SportCategory
from .models import Club
from .forms import ClubForm

class ClubsIndexView(ListView):
    def get_queryset(self):
        return Club.objects.published()


class ClubDetailView(DetailView):
    def get_queryset(self):
        return Club.objects.published()


class ClubsBySportView(ListView):
    template_name = 'clubs/clubs_by_sport.html'

    def dispatch(self, request, *args, **kwargs):
        self.sport = None
        self.sport_category = None

        try:
            self.sport = Sport.objects.get(slug=self.kwargs['slug'])
        except Sport.DoesNotExist:
            try:
                self.sport_category = SportCategory.objects.get(slug=self.kwargs['slug'])
            except SportCategory.DoesNotExist:
                raise Http404
        return super(ClubsBySportView, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        if self.sport:
            return Club.objects.published().filter(sports=self.sport)

        return Club.objects.published().filter(sports__categories=self.sport_category).distinct()


class ClubCoachesView(ListView):
    def dispatch(self, request, *args, **kwargs):
        self.club = Club.objects.published().get(slug=kwargs['slug'])
        return super(ClubCoachesView, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        return self.club.coaches.all()

    def get_context_data(self, **kwargs):
        ctx = super(ClubCoachesView, self).get_context_data(**kwargs)
        ctx['club'] = self.club
        return ctx


class CreateClubView(CreateView):
    form_class = ClubForm
    model = Club

sclubs/exercises/views.py
__author__ = 'Evgeniy Tatarintsev'

sclubs/generic/views.py
__author__ = 'Evgeniy Tatarintsev'
from django.views.generic import TemplateView


class HomePageView(TemplateView):
    template_name = 'index.html'

sclubs/news/views.py
__author__ = 'john'
from django.views.generic import ListView, DetailView
from django.conf import settings

from .models import Entry


class EntryListView(ListView):
    paginate_by = getattr(settings, 'NEWS_ON_PAGE', 10)

    def get_queryset(self):
        filters = {}

        if 'sport' in self.request.GET:
            filters['sports__slug'] = self.request.GET['sport']

        return Entry.objects.active(**filters)


class EntryDetail(DetailView):
    def get_queryset(self):
        if 'preview' in self.request.GET and self.request.user.is_staff:
            return Entry.objects.all()

        return Entry.objects.active()

sclubs/templates/clubs/around.html
{% extends "base.html" %}

{% load pymorphy_tags sekizai_tags %}

{% block page_title %}Поиск клуба по-близости{% endblock %}

{% block page_description %}Поиск клуба по-близости{% endblock %}

{% block page_keywords %}Поиск клуба по-близости{% endblock %}

{% block search_club %}
    <div class="search-club">
        <span><a href="{% url "clubs:around" %}">Поиск клуба по близости</a></span>
    </div>
{% endblock %}

{% block content %}
	<div class="form-description">
		Здесь можно подобрать интересующий вас спортивный клуб, находящийся не далее заданного расстояния от вашего дома.
			<form class="create-club-form" method="GET">
			<table>
			<tr>
				<td>
					<select id="id_city" class="field-form" name="city" placeholder="Ваш город">
						<option class="selected" selected="selected" value="{{ request.location.pk }}">{{ request.location }}</option>
					</select>
				</td>
			</tr>
			<tr>
				<td><input id="id_address" class="field-form" type="text" placeholder="Ваш адрес" maxlength="100" name="address" value="{{request.GET.address}}"></td>
			</tr>
			<tr>
				<td>
					<select id="id_sports" class="field-form" multiple="multiple" name="sports">
						{% for sport in sports %}
						<option class="selected" selected="selected" value="{{ sport.pk }}">{{ sport }}</option>
						{% endfor %}
					</select>
				</td>
			</tr>
			<tr>
				<td><input id="id_distance" class="field-form" type="text" placeholder="Расстояние до клуба в км" maxlength="3" name="distance" value="{{ request.GET.distance }}"></td>
			</tr>
			<tr>
				<td><button class="create-event-button" type="submit">Найти</button></td>
			</tr>
			
			
			</table>
		</form>
	</div>

    {% include "clubs/include_list.html" %}
    
    {% addtoblock "css" %}
   <link rel="stylesheet" type="text/css" media="all" href="{{MEDIA_URL}}css/fcbkinput.css"> 
{% endaddtoblock %}
{% addtoblock "js" %}
    <script type="text/javascript" src="{{MEDIA_URL}}js/jquery.fcbkcomplete.js"></script>
    <script>
        $(document).ready(function(){
         $("#id_city").fcbkcomplete({
            json_url:'{% url "get-city-list" %}',
            first_selected:false,
            filter_hide : true,
            filter_case:false,
            bricket: false,
            maxitems: 1,
            complete_text:"Введите название города",
            });
           
         $("#id_sports").fcbkcomplete({
            json_url:'{% url "get-sport-list" %}',
            first_selected:false,
            filter_hide : true,
            filter_case:false,
            bricket: false,
            maxitems: 100,
            complete_text:"Введите вид спорта",
            });
    
       });
   </script>
{% endaddtoblock %}
    
{% endblock %}

{% block  breadcrumbs %}
    {% if not city %}
        <h1>Поиск клуба по-близости</h1>
    {% else %}
        <h1>Клубы {{ city|inflect:"рд" }} в близи {{ address }}</h1>
    {% endif %}
{% endblock %}

sclubs/templates/clubs/club_confirm_delete.html
{% extends "base.html" %}

{% load tagging_tags  thumbnail %}



{% block  breadcrumbs %}
    <h1>Удаление клуба</h1>
{% endblock %}

{% block content %}
<div class="main-content article-text">

    <h1>{{ club.title }}</h1>
    <div class="info">
        <a href="#" class="date">{{ club.date|date:"j E - H:i" }}</a>
        <a href="#commetns" class="comments">{{ club.comments.count }}</a>
        {% tags_for_object club as tag_list %}
        {% if tag_list %}
        <span class="tags">
            {% for tag in tag_list %}
                <a href="/tag/all/{{tag}}">{{tag}}</a>{% if not forloop.last %}, {% endif %}
            {% endfor %}
        </span>
        {% endif %}
    </div>
    <div class="article-content">
        {{ club.description }}
    </div>
    <div class="article-contacts">
        <strong>Адрес: </strong> {{ club.address }} <strong>тел.</strong> {{ club.phones }}
    </div>
    <div class="article-site">
        <strong>Сайт: </strong> <a href="{{ club.site }}">{{ club.site }}</a>
    </div>
    

    <div class="article-map">
        
    </div>
    
</div>
<form method="POST" action="">{% csrf_token %}
    <button type="submit" class="create-event-button">Удалить</button>
</form>
{% endblock %}

sclubs/templates/clubs/club_form.html
{% extends "base.html" %}

{% load i18n sekizai_tags thumbnail %}

{% block meta %}
    <title>
        {% if club %}
            {% trans "Edit club" %}
        {% else %}
            {% trans "Create club" %}
        {% endif %}
    </title>
{% endblock %}

{% block  breadcrumbs %}
    <h1>
        {% if club %}
            {% trans "Edit club" %}
        {% else %}
            {% trans "Create club" %}
        {% endif %}
    </h1>
{% endblock %}

{% block search_club %}
    <div class="search-club">
        <span><a href="{#% url "clubs:around" %#}">{% trans "Find clubs around" %}</a></span>
    </div>
{% endblock %}

{% block content %}
{% if not club %}
    <div class="form-description">
    Здесь вы можете добавить спортивный клуб, секцию или целый спорткомплекс в каталог спортивных клубов. После добавления вы всегда сможете отредактировать информацию, если нашли ошибку.<br>
    О вашей спортивной секции узнают ещё больше людей. Вам будет проще набрать группу и привлечь новых спортсменов, которые всегда смогут найти на нашем сайте контакты и связаться с Вами.
    </div>
{% endif %}

<form class="create-club-form common-form" action="" method="POST" enctype="multipart/form-data"> {% csrf_token %}
    {{ form }}
</form>

{% endblock %}

{% block banner1 %}

{% endblock banner1 %}

sclubs/templates/clubs/club_include.html
{% load thumbnail %}


<div class="wrap-news{% if forloop.last %} list-last{% endif %}">
    <table>
        <tr>
            <td class="col1">
               {% if club.logo %}
                <div class="td-img">
                    {% thumbnail club.logo "140x100" crop="center" as img %}
                        <img src="{{ img.url }}" alt="{{ club.title }}">
                    {% endthumbnail %}
                </div>
                {% elif club.screenshot %}
                <div class="td-img">
                    {#% thumbnail club.screenshot "140x100" crop="center" as im %#}
                        <img src="{{im.url}}" alt="{{club.title}}">
                    {#% endthumbnail %#}
                </div>
                {% endif %}
            </td>
            <td>
                <h1><a href="{{ club.get_absolute_url }}">{{ club.get_title }}</a></h1>
                <div class="info">
                    <span class="tags tag-info"><a href="{#% url "filters:tagged-clubs" %#}?city={{ club.city.id }}">{{club.city}}</a>
                        {% for sport in club.sports.all %}, <a href="{% url "clubs:sport" slug=sport.slug %}">{{ sport }}</a>{% endfor %}
                    </span>
                </div>
                <div class="text-news">
                    <div class="article-contacts">
                        <strong>Адрес: </strong> {{ club.city }}, {{ club.address }}.{% if club.phones %} <strong>тел. {{ club.phones }}{% endif %}</strong>
                    </div>
                    {% if club.site %}
                    <div class="article-site">
                        <strong>Сайт: </strong> <noindex><a target="__blank" href="{{ club.site }}" rel="nofollow">{{ club.site }}</a></noindex>
                    </div>
                    {% endif %}
                </div>
            </td>
        </tr>
    </table>
</div>

sclubs/templates/clubs/club_list.html
{% extends "base.html" %}


{% block content %}
    <div class="main-content">
    {% for club in club_list %}
        {% include "clubs/club_include.html" %}
    {% endfor %}
</div>
{% endblock %}

{% block  breadcrumbs %}
    <h1>Все спортивные клубы</h1>
{% endblock %}

{% block footer_link %}
    <a href="{#% url "clubs:sitemap" %#}">Клубы в городах</a>
{% endblock footer_link %}


{% block search_club %}
    <div class="search-club">
        <span><a href="{#% url "clubs:around" %#}">Поиск клуба по близости</a></span>
    </div>
{% endblock %}

sclubs/templates/clubs/club_menu.html
<div class="content-nav">
    <div class="paddin-content-nav">
        <div class="wrap-content-nav">
            <table>
                <tr>
                    <td class="img-nav">
                    </td>
                    <td>
                        <div class="text-nav">
                            {% if request.user in club.admins.all %}
                            <a class="add-item-nav" href="{#% url "clubs:create" %#}">Добавить</a>
                            {% endif %}
                            <a href="{% url "clubs:coaches" slug=club.slug %}">Тренеры</a>
                        </div>
                    </td>
                </tr>
            </table>
        </div>
    </div>

    <div class="paddin-content-nav">
        <div class="wrap-content-nav">
            <table>
                <tr>
                    <td class="img-nav">
                    </td>
                    <td>
                        <div class="text-nav">
                            {% if request.user in club.admins.all %}
                            <a class="add-item-nav" href="{#% url "clubs:create" %#}">Добавить</a>
                            {% endif %}
                            <a href="{#% url "accounts:events" pk=user.pk %#}">Мои события</a>
                        </div>
                    </td>
                </tr>
            </table>
        </div>
    </div>

    <div class="paddin-content-nav">
        <div class="wrap-content-nav">
            <table>
                <tr>
                    <td class="img-nav">
                    </td>
                    <td>
                        <div class="text-nav">
                            {% if request.user in club.admins.all %}
                            <a class="add-item-nav" href="{#% url "clubs:create" %#}">Добавить</a>
                            {% endif %}
                            <a href="{#% url "accounts:news" pk=user.pk %#}">Мои новости</a>
                        </div>
                    </td>
                </tr>
            </table>
        </div>
    </div>

    {% if request.user in club.admins.all %}
    <div class="paddin-content-nav">
        <div class="wrap-content-nav list-last">
            <table>
                <tr>
                    <td class="img-nav">
                    </td>
                    <td>
                        <div class="text-nav">
                            <a href="{#% url "accounts:settings" pk=user.pk %#}">Настройки</a>
                        </div>
                    </td>
                </tr>
            </table>
        </div>
    </div>
    {% endif %}
</div>

sclubs/templates/clubs/clubs_by_sport.html
{% extends "base.html" %}


{% block content %}
    <div class="main-content">
    {% for club in club_list %}
        {% include "clubs/club_include.html" %}
    {% endfor %}
</div>
{% endblock %}

{% block  breadcrumbs %}
    <h1>Все спортивные клубы</h1>
{% endblock %}

{% block footer_link %}
    <a href="{#% url "clubs:sitemap" %#}">Клубы в городах</a>
{% endblock footer_link %}


{% block search_club %}
    <div class="search-club">
        <span><a href="{#% url "clubs:around" %#}">Поиск клуба по близости</a></span>
    </div>
{% endblock %}