sclubs/clubs/urls.py
__author__ = 'Evgeniy Tatarintsev'
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
from .views import (ClubDetailView,
                    ClubsIndexView,
                    ClubsBySportView,
                    ClubCoachesView,
                    CreateClubView)

urlpatterns = patterns('',
    url(r'^$', ClubsIndexView.as_view(), name='index'),
    url(r'^create/$', login_required(CreateClubView.as_view()), name='create'),
    #url(r'^category/(?P<slug>[-a-zA-Z0-9_]+)/$', CategoryDetailView.as_view(), name='category'),
    url(r'^sport/(?P<slug>[-a-zA-Z0-9_]+)/$', ClubsBySportView.as_view(), name='sport'),
    url(r'^(?P<slug>[-a-zA-Z0-9_]+)/$', ClubDetailView.as_view(), name='detail'),
    url(r'^(?P<slug>[-a-zA-Z0-9_]+)/coaches/$', ClubCoachesView.as_view(), name='coaches'),
)

sclubs/news/urls.py
__author__ = 'Evgeniy Tatarintsev'
from django.conf.urls import patterns, url

from .views import EntryListView, EntryDetail

urlpatterns = patterns('',
    url(r'^$', EntryListView.as_view(), name='index'),
    url(r'^(?P<slug>[-a-zA-Z0-9_]+)/$', EntryDetail.as_view(), name='detail'),
)

sclubs/templates/designer/urls.py
from django.conf.urls import patterns, include, url

from django.conf import settings
from django.contrib import admin
admin.autodiscover()

from {{domain}}.index import HomeView

urlpatterns = patterns('',
    (r'^grappelli/', include('grappelli.urls')),
    #url(r'^admin_tools/', include('admin_tools.urls')),
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^articles/', include('scms.articles.urls', namespace='articles')),
    url(r'^news/', include('scms.news.urls', namespace='news')),
    url(r'^gallery/', include('scms.gallery.urls', namespace='gallery')),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('scms.static_page.urls', namespace='static-pages')),
)

sclubs/urls.py
__author__ = 'Evgeniy Tatarintsev'
from django.conf.urls import patterns, url, include
from django.contrib import admin
from django.conf import settings

from sclubs.generic.views import HomePageView

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^ckeditor/', include('ckeditor.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^hit/update/$', 'hitcount.views.update_hit_count_ajax',
                                            name='hitcount_update_ajax'),

    url(r'^$', HomePageView.as_view(), name='home-page'),
    url(r'^news/', include('sclubs.news.urls', namespace='news')),
    url(r'^articles/', include('sclubs.articles.urls', namespace='articles')),
    url(r'^clubs/', include('sclubs.clubs.urls', namespace='clubs')),
    url(r'^accounts/', include('sclubs.accounts.urls', namespace='accounts')),

)


if settings.DEBUG:
    urlpatterns += patterns("",
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
            'show_indexes': True}),
    )

sclubs/utils/urls.py
__author__ = 'Evgeniy Tatarintsev'
import re
import unicodedata

from django.core.exceptions import ObjectDoesNotExist
from django.core.urlresolvers import (resolve, reverse, NoReverseMatch,
                                      get_script_prefix)
from django.shortcuts import redirect
from django.utils.encoding import smart_unicode
from django.utils import translation

from sclubs import settings
from sclubs.utils.importing import import_dotted_path


def admin_url(model, url, object_id=None):
    """
    Returns the URL for the given model and admin url name.
    """
    opts = model._meta
    url = "admin:%s_%s_%s" % (opts.app_label, opts.object_name.lower(), url)
    args = ()
    if object_id is not None:
        args = (object_id,)
    return reverse(url, args=args)


def home_slug():
    """
    Returns the slug arg defined for the ``home`` urlpattern, which
    is the definitive source of the ``url`` field defined for an
    editable homepage object.
    """
    prefix = get_script_prefix()
    slug = reverse("home")
    if slug.startswith(prefix):
        slug = '/' + slug[len(prefix):]
    try:
        return resolve(slug).kwargs["slug"]
    except KeyError:
        return slug




def unique_slug(queryset, slug_field, slug):
    """
    Ensures a slug is unique for the given queryset, appending
    an integer to its end until the slug is unique.
    """
    i = 0
    while True:
        if i > 0:
            if i > 1:
                slug = slug.rsplit("-", 1)[0]
            slug = "%s-%s" % (slug, i)
        try:
            queryset.get(**{slug_field: slug})
        except ObjectDoesNotExist:
            break
        i += 1
    return slug


def login_redirect(request):
    """
    Returns the redirect response for login/signup. Favors:
    - next param
    - LOGIN_REDIRECT_URL setting
    - homepage
    """
    ignorable_nexts = ("",)
    if "sclubs.accounts" in settings.INSTALLED_APPS:
        from sclubs.accounts import urls
        ignorable_nexts += (urls.SIGNUP_URL, urls.LOGIN_URL, urls.LOGOUT_URL)
    next = request.REQUEST.get("next", "")
    if next in ignorable_nexts:
        try:
            next = reverse(settings.LOGIN_REDIRECT_URL)
        except NoReverseMatch:
            next = "/"
    return redirect(next)


def path_to_slug(path):
    """
    Removes everything from the given URL path, including
    language code and ``PAGES_SLUG`` if any is set, returning
    a slug that would match a ``Page`` instance's slug.
    """
    from mezzanine.urls import PAGES_SLUG
    lang_code = translation.get_language_from_path(path)
    for prefix in (lang_code, settings.SITE_PREFIX, PAGES_SLUG):
        if prefix:
            path = path.replace(prefix, "", 1)
    return path.strip("/") or "/"

sclubs/accounts/models.py
__author__ = 'Evgeniy Tatarintsev'
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.utils.http import urlquote
from django.utils import timezone

from sclubs.settings.conf import DEFAULT_USER_ID_LENGTH, USER_ID_PREFIX
from .managers import UserManager


def gen_user_id(pk):
    """
    Generate verbose user id
    """
    blank_space = DEFAULT_USER_ID_LENGTH - len(USER_ID_PREFIX) - len(str(pk))
    return USER_ID_PREFIX + \
           ''.join(['0' for i in range(blank_space)]) + \
           str(pk)


class User(AbstractBaseUser, PermissionsMixin):
    """
    User object for sclubs project
    use email as username
    """
    email = models.EmailField(_('email address'), unique=True, db_index=True,
                              null=True, blank=True)
    slug = models.SlugField(_('Verbose user ID'), max_length=50, unique=True)
    is_active = models.BooleanField(_('active'), default=True,
        help_text=_('Designates whether this user should be treated as '
                    'active. Unselect this instead of deleting accounts.'))
    is_staff = models.BooleanField(_('staff status'), default=False,
        help_text=_('Designates whether the user can log into this admin '
                    'site.'))
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)



    USERNAME_FIELD = 'email'
    objects = UserManager()

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def save(self, *args, **kwargs):
        super(User, self).save(*args, **kwargs)

        if not self.slug:
            self.slug = gen_user_id(self.pk)
            self.save(update_fields=['slug', ])

    def email_user(self, subject, message, from_email=None):
        """
        Sends an email to this User.
        Email is sent asynchronously
        """
        raise NotImplementedError

    def get_absolute_url(self):
        return "/users/%s/" % urlquote(self.username)

    def get_full_name(self):
        """
        Returns the first_name plus the last_name, with a space in between.
        """
        return self.email

    def get_short_name(self):
        "Returns the short name for the user."
        return self.email

sclubs/exercises/models.py
__author__ = 'Evgeniy Tatarintsev'

sclubs/clubs/forms.py
#-*- coding: utf-8 -*-
__author__ = 'Evgeniy Tatarintsev'
from django import forms

from .models import Club


class ClubForm(forms.ModelForm):
    class Meta:
        model = Club
        fields = ('title', 'logo', 'content', 'sports')

sclubs/core/forms.py
__author__ = 'john'
from uuid import uuid4

from django import forms
from django.forms.extras.widgets import SelectDateWidget
from django.utils.safestring import mark_safe
from django.utils.translation import ugettext as _
from django.contrib.staticfiles.storage import staticfiles_storage
from django.conf import settings

from sclubs.core.models import Orderable



class TinyMceWidget(forms.Textarea):
    """
    Setup the JS files and targetting CSS class for a textarea to
    use TinyMCE.
    """

    class Media:
        js = _tinymce_js

    def __init__(self, *args, **kwargs):
        super(TinyMceWidget, self).__init__(*args, **kwargs)
        self.attrs["class"] = "mceEditor"


class OrderWidget(forms.HiddenInput):
    """
    Add up and down arrows for ordering controls next to a hidden
    form field.
    """
    def render(self, *args, **kwargs):
        rendered = super(OrderWidget, self).render(*args, **kwargs)
        arrows = ["<img src='%sadmin/img/admin/arrow-%s.gif' />" %
            (settings.STATIC_URL, arrow) for arrow in ("up", "down")]
        arrows = "<span class='ordering'>%s</span>" % "".join(arrows)
        return rendered + mark_safe(arrows)


class DynamicInlineAdminForm(forms.ModelForm):
    """
    Form for ``DynamicInlineAdmin`` that can be collapsed and sorted
    with drag and drop using ``OrderWidget``.
    """

    class Media:
        js = ("mezzanine/js/jquery-ui-1.9.1.custom.min.js",
              "mezzanine/js/admin/dynamic_inline.js",)

    def __init__(self, *args, **kwargs):
        super(DynamicInlineAdminForm, self).__init__(*args, **kwargs)
        if issubclass(self._meta.model, Orderable):
            self.fields["_order"] = forms.CharField(label=_("Order"),
                widget=OrderWidget, required=False)


class SplitSelectDateTimeWidget(forms.SplitDateTimeWidget):
    """
    Combines Django's ``SelectDateTimeWidget`` and ``SelectDateWidget``.
    """
    def __init__(self, attrs=None, date_format=None, time_format=None):
        date_widget = SelectDateWidget(attrs=attrs)
        time_widget = forms.TimeInput(attrs=attrs, format=time_format)
        forms.MultiWidget.__init__(self, (date_widget, time_widget), attrs)


class CheckboxSelectMultiple(forms.CheckboxSelectMultiple):
    """
    Wraps render with a CSS class for styling.
    """
    def render(self, *args, **kwargs):
        rendered = super(CheckboxSelectMultiple, self).render(*args, **kwargs)
        return mark_safe("<span class='multicheckbox'>%s</span>" % rendered)


def get_edit_form(obj, field_names, data=None, files=None):
    """
    Returns the in-line editing form for editing a single model field.
    """

    # Map these form fields to their types defined in the forms app so
    # we can make use of their custom widgets.
    from mezzanine.forms import fields
    widget_overrides = {
        forms.DateField: fields.DATE,
        forms.DateTimeField: fields.DATE_TIME,
        forms.EmailField: fields.EMAIL,
    }

    class EditForm(forms.ModelForm):
        """
        In-line editing form for editing a single model field.
        """

        app = forms.CharField(widget=forms.HiddenInput)
        model = forms.CharField(widget=forms.HiddenInput)
        id = forms.CharField(widget=forms.HiddenInput)
        fields = forms.CharField(widget=forms.HiddenInput)

        class Meta:
            model = obj.__class__
            fields = field_names.split(",")

        def __init__(self, *args, **kwargs):
            super(EditForm, self).__init__(*args, **kwargs)
            self.uuid = str(uuid4())
            for f in self.fields.keys():
                field_class = self.fields[f].__class__
                try:
                    field_type = widget_overrides[field_class]
                except KeyError:
                    pass
                else:
                    self.fields[f].widget = fields.WIDGETS[field_type]()
                css_class = self.fields[f].widget.attrs.get("class", "")
                css_class += " " + field_class.__name__.lower()
                self.fields[f].widget.attrs["class"] = css_class
                self.fields[f].widget.attrs["id"] = "%s-%s" % (f, self.uuid)
                if settings.FORMS_USE_HTML5 and self.fields[f].required:
                    self.fields[f].widget.attrs["required"] = ""

    initial = {"app": obj._meta.app_label, "id": obj.id,
               "fields": field_names, "model": obj._meta.object_name.lower()}
    return EditForm(instance=obj, initial=initial, data=data, files=files)

sclubs/accounts/views.py
#-*- coding: utf-8 -*-
__author__ = 'Evgeniy Tatarintsev'
from django.views.generic import DetailView

from .models import User


class UserProfileView(DetailView):
    context_object_name = "profile_owner"

    def get_queryset(self):
        return User.objects.active()

    def get_context_data(self, **kwargs):
        ctx = super(UserProfileView, self).get_context_data(**kwargs)
        ctx['can_edit'] = self.request.user == self.object
        return ctx

sclubs/articles/views.py
__author__ = 'Evgeniy Tatarintsev'
from django.utils.timezone import now
from django.views.generic import ListView, DetailView
from django.http import Http404

from models import Article, Aphorism, Category
from sclubs.generic.models import Keyword


class ArticleDetailView(DetailView):
    def get_queryset(self):
        return Article.objects.published()

    def get_object(self, queryset=None):
        article = self.get_queryset().filter(slug=self.kwargs['slug'])
        if not article:
            raise Http404
        article.update(last_view=now())
        return article[0]


class CategoryDetailView(DetailView):
    def get_queryset(self):
        return Category.objects.published()


class CategoryListView(ListView):
    def get_queryset(self):
        return Category.objects.published()


class TaggedArticlesView(DetailView):
    model = Keyword
    template_name = 'articles/tagged_list.html'
    context_object_name = 'tag'

sclubs/clubs/views.py
#-*- coding: utf-8 -*-
__author__ = 'Evgeniy Tatarintsev'
from django.views.generic import DetailView, ListView, CreateView, UpdateView
from django.http import Http404
from django.db.models import Q

from sclubs.generic.models import Sport, SportCategory
from .models import Club
from .forms import ClubForm

class ClubsIndexView(ListView):
    def get_queryset(self):
        return Club.objects.published()


class ClubDetailView(DetailView):
    def get_queryset(self):
        return Club.objects.published()


class ClubsBySportView(ListView):
    template_name = 'clubs/clubs_by_sport.html'

    def dispatch(self, request, *args, **kwargs):
        self.sport = None
        self.sport_category = None

        try:
            self.sport = Sport.objects.get(slug=self.kwargs['slug'])
        except Sport.DoesNotExist:
            try:
                self.sport_category = SportCategory.objects.get(slug=self.kwargs['slug'])
            except SportCategory.DoesNotExist:
                raise Http404
        return super(ClubsBySportView, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        if self.sport:
            return Club.objects.published().filter(sports=self.sport)

        return Club.objects.published().filter(sports__categories=self.sport_category).distinct()


class ClubCoachesView(ListView):
    def dispatch(self, request, *args, **kwargs):
        self.club = Club.objects.published().get(slug=kwargs['slug'])
        return super(ClubCoachesView, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        return self.club.coaches.all()

    def get_context_data(self, **kwargs):
        ctx = super(ClubCoachesView, self).get_context_data(**kwargs)
        ctx['club'] = self.club
        return ctx


class CreateClubView(CreateView):
    form_class = ClubForm
    model = Club

sclubs/exercises/views.py
__author__ = 'Evgeniy Tatarintsev'

sclubs/generic/views.py
__author__ = 'Evgeniy Tatarintsev'
from django.views.generic import TemplateView


class HomePageView(TemplateView):
    template_name = 'index.html'

sclubs/news/views.py
__author__ = 'john'
from django.views.generic import ListView, DetailView
from django.conf import settings

from .models import Entry


class EntryListView(ListView):
    paginate_by = getattr(settings, 'NEWS_ON_PAGE', 10)

    def get_queryset(self):
        filters = {}

        if 'sport' in self.request.GET:
            filters['sports__slug'] = self.request.GET['sport']

        return Entry.objects.active(**filters)


class EntryDetail(DetailView):
    def get_queryset(self):
        if 'preview' in self.request.GET and self.request.user.is_staff:
            return Entry.objects.all()

        return Entry.objects.active()

sclubs/templates/gallery/album_detail.html
{% extends "gallery/base_list.html" %}

{% load tagging_tags thumbnail %}
{% load sekizai_tags hitcount_tags  %}


{% block page_title %}
    {% if filter == "popular" %}
        {{ album.title }} популярные
    {% elif filter == "video" %}
        {{ album.title }} видео
    {% elif filter == "foto" %}
        {{ album.title }} фото
    {% else %}
        {{ album.title }} фото и видео
    {% endif %}
{% endblock %}

{% block page_description %}
    {% if filter == "popular" %}
        {{ album.title }} популярные
    {% elif filter == "video" %}
        {{ album.title }} видео
    {% elif filter == "foto" %}
        {{ album.title }} фото
    {% else %}
        {{ album.title }} фото и видео
    {% endif %}
{% endblock %}


{% block page_keywords %}
    {% if filter == "popular" %}
        {{ album.title }} популярные
    {% elif filter == "video" %}
        {{ album.title }} видео
    {% elif filter == "foto" %}
        {{ album.title }} фото
    {% else %}
        {{ album.title }} фото и видео
    {% endif %}
{% endblock %}


{% block  breadcrumbs %}
    {% if filter == "popular" %}
    
    {% elif filter == "video" %}
    {% elif filter == "foto" %}
    {% else %}
        <h1>{{ album.title }}</h1>
    {% endif %}
{% endblock %}

{% block content %}
    {% addtoblock "js" %}
    <script type="text/javascript">
        $(document).ready(function() {
            {% get_hit_count_javascript for album %}
        });
    </script>
    {% endaddtoblock %}
    {% csrf_token %}
    
    {{ block.super }}

{% endblock %}

sclubs/templates/gallery/album_list.html
{% extends "gallery/base_list.html" %}

{% load tagging_tags thumbnail menu_tags %}

{% block page_title %}Видео и фото альбомы спортивных соревнований{% endblock %}

{% block page_description %}Видео и фото альбомы спортивных соревнований{% endblock %}

{% block page_keywords %}Видео и фото альбомы спортивных соревнований{% endblock %}


{% block  breadcrumbs %}
    <h1>Медиа</h1>
{% endblock %}

{% block content %}
<div class="main-content">
    <div class="media-content">
        <table>
            <tr>
            {% for album in item_list %}
            {% if forloop.counter0|divisibleby:"3" %}<tr>{% endif %}
                <td>
                    <div class="wrap-media-img">
                        <a href="{{ album.get_absolute_url }}">
                            
                            {% thumbnail  album.get_head "180x130" crop="center" as im %}
                                <img src="{{im.url}}" alt="{{ album.title }}">
                            {% endthumbnail %}
                            
                        <div class="media-desc">
                            <a href="{{ album.get_absolute_url }}">{{ album.title }}</a>
                        </div>
                    </div>
                </td>
                
            {% if forloop.counter|divisibleby:"3" or forloop.last %}</tr>{% endif %}
            {% endfor %}
        </table>
    </div>
</div>
{% endblock %}

sclubs/templates/gallery/base_list.html
{% extends "base.html" %}

{% load tagging_tags thumbnail %}
{% load sekizai_tags hitcount_tags  %}


{% block page_title %}base list{% endblock %}

{% block  breadcrumbs %}
    <h1>{{ album.title }}</h1>
{% endblock %}


{% block filters %}
   {% addtoblock "css" %}
        <link rel="stylesheet" type="text/css" media="all" href="{{STATIC_URL}}css/highslide.css">
        <link rel="stylesheet" type="text/css" media="all" href="{{STATIC_URL}}css/highslide-ie6.css">
    {% endaddtoblock %}
    
    {% addtoblock "js" %}
        <script type="text/javascript" src="{{STATIC_URL}}js/highslide-full.js"></script> 
    {% endaddtoblock %}

<div class="filter-tab">
    <div class="left-bg{% if filter == "all" %} bg-active{% endif %}">
        <div class="right-bg{% if filter == "all" %} bg-active{% endif %}">
            <div class="fl-tab center-bg {% if filter == "all" %} bg-active{% endif %}">
                {% if album %}
                <a href="{% url "gallery:album-detail" pk=album.id %}" id="fl-tab1">Все</a>
                {% else %}
                <a href="{% url "gallery:index" %}" id="fl-tab1">Альбомы</a>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="left-bg{% if filter == "popular" %} bg-active{% endif %}">
        <div class="right-bg{% if filter == "popular" %} bg-active{% endif %}">
            <div class="fl-tab center-bg{% if filter == "popular" %} bg-active{% endif %}">
                {% if album %}
                <a href="{% url "gallery:album-filter" pk=album.id filter="popular" %}" id="fl-tab2">Популярные</a>
                {% else %}
                <a href="{% url "gallery:media-filter" filter="popular" %}" id="fl-tab2">Популярное</a>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="left-bg{% if filter == "video" %} bg-active{% endif %}">
        <div class="right-bg{% if filter == "video" %} bg-active{% endif %}">
            <div class="fl-tab center-bg{% if filter == "video" %} bg-active{% endif %}">
                {% if album %}
                <a href="{% url "gallery:album-filter" pk=album.id filter="video" %}" id="fl-tab3">Видео</a>
                {% else %}
                <a href="{% url "gallery:media-filter" filter="video" %}" id="fl-tab3">Видео</a>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="left-bg{% if filter == "foto" %} bg-active{% endif %}">
        <div class="right-bg{% if filter == "foto" %} bg-active{% endif %}">
            <div class="fl-tab center-bg{% if filter == "foto" %} bg-active{% endif %}">
                {% if album %}
                <a href="{% url "gallery:album-filter" pk=album.id filter="foto" %}" id="fl-tab4">Фото</a>
                {% else %}
                <a href="{% url "gallery:media-filter" filter="foto" %}" id="fl-tab4">Фото</a>
                {% endif %}

            </div>
        </div>
    </div>

</div>
{% endblock %}


{% block content %}

<div class="main-content">
    <div class="media-content">
        <table>
            <tr>
            {% for item in item_list %}
            {% if forloop.counter0|divisibleby:"3" %}<tr>{% endif %}
                <td>
                    <div class="wrap-media-img">
                        
                        {% if item.image %}
                        <a class="thumb highslide" onclick="return hs.expand(this)" href="{{ item.image.url }}">
                            {% thumbnail item.image "180x130" crop="center" as im %}
                                <img src="{{im.url}}" alt="{{item.title|default:item.album.title}}">
                            {% endthumbnail %}
                        </a>
                        {% else %}
                        <a  href="{{ item.get_absolute_url }}">
                            {% thumbnail item.preview "180x130" crop="center" as im %}
                                <img src="{{im.url}}" alt="{{item.title|default:item.album.title}}">
                            {% endthumbnail %}
                        </a>
                        {% endif %}
                        <div class="media-desc">
                            <a href="{{ item.get_absolute_url }}">{{ item.title|default:item.album.title }}</a>
                        </div>
                        <div class="media-icon"><img src="{{ STATIC_URL }}img/{% if item.image %}photo{% else %}video{% endif %}-icon.png" alt=""></div>
                    </div>
                </td>
                
            {% if forloop.counter|divisibleby:"3" or forloop.last %}</tr>{% endif %}
            {% empty %}
            {% if filter == "video" %}
                <td>Видео материалы не найдены</td>
            {% elif filter == "foto" %}
                <td>Изображения не найдены</td>
            {% elif filter == "popular" %}
                <td>Нет популярных файлов</td>
            {% else %}
                <td>Альбом пуст</td>
            {% endif %}
            </tr>
            {% endfor %}
        </table>
    </div>
</div>
{% endblock %}

sclubs/templates/gallery/foto_detail.html
{% extends "base.html" %}

{% load tagging_tags thumbnail %}
{% load sekizai_tags hitcount_tags comments %}

{% block page_title %}{% if foto.title %}{{ foto.title }} фото{% else %}Фото {{ foto.id }} из альбома {{foto.album.title}}{% endif %}{% endblock %}

{% block page_description %}{% if foto.title %}{{ foto.title }} фото{% else %}Фото {{ foto.id }} из альбома {{foto.album.title}}{% endif %}{% endblock %}

{% block page_keywords %}
    {% if foto.title %}{{ foto.title }} фото{% else %}Фото {{ foto.id }} из альбома {{foto.album.title}}{% endif %}, 
    {% if foto.city %}{{ foto.city }}{% elif foto.album.city %}{{ foto.album.city }}{% endif %}, 
    {% for sport in foto.sports.all %}{{ sport.tag }},{% endfor %}
{% endblock %}

{% block  breadcrumbs %}
    <h1>{{ foto.title|default:foto.album }}</h1>
{% endblock %}


{% block content %}

    {# Enable hit counting #}
    {% addtoblock "js" %}
    <script type="text/javascript">
        $(document).ready(function() {
            {% get_hit_count_javascript for foto %}
        });
    </script>
    {% endaddtoblock %}
    {% csrf_token %}
<div class="main-content">


    <div class="media-content">
        <h2>{{ foto.title }}</h2>
        <a class="back" href="{{ foto.album.get_absolute_url }}">&larr; к альбому</a>
        <span class="date">{{ foto.date|date:"Y" }}</span>
        <div class="video-block">
            {% thumbnail foto.image "620" quality=80 as im %}
            <img src="{{ im.url }}">
            {% endthumbnail %}
        </div>
        <div class="info">
            <span class="tags">
                    {% if foto.city %}
                    <a href="{% url "filters:tagged-media" %}?city={{foto.city.id}}">{{ foto.city }}</a>,
                    {% elif foto.album.city %}
                    <a href="{% url "filters:tagged-media" %}?city={{foto.album.city.id}}">{{ foto.album.city }}</a>,
                    {% endif %}
                    {% for sport in foto.sports.all|default:foto.album.sports.all %}
                        <a href="{% url "filters:tagged-media" %}?{{sport.tag.id}}=on">{{ sport }}</a>
                    {% endfor %}
            </span>
        </div>
        

                            
    </div>
</div>

{% endblock %}

{% block comments %}
    {% if not foto.enable_comments %}
        <div class="comments-block">
            <span>Комментарии:</span>
            {% render_comment_list for foto %}
            {% render_comment_form for foto %}
        </div>
    {% endif %}
{% endblock %}

sclubs/templates/gallery/foto_list.html
{% extends "gallery/base_list.html" %}

{% load tagging_tags thumbnail %}
{% load sekizai_tags hitcount_tags  %}

{% block page_title %}Последние спортивные фото{% endblock %}

{% block page_description %}Последние фото со спортивных соревнований{% endblock %}

{% block page_keywords %}Последние фото, спортивные соревнования{% endblock %}

{% block  breadcrumbs %}
    <h1>Последние фото</h1>
{% endblock %}

sclubs/templates/gallery/popular_list.html
{% extends "gallery/base_list.html" %}

{% load tagging_tags thumbnail %}
{% load sekizai_tags hitcount_tags  %}


{% block page_title %}Популярное спортивное фото и видео {% endblock %}


{% block page_description %}Популярное фото и видео со спортивных соревнований{% endblock %}

{% block page_keywords %}Популярное фото и видео, спортивные соревнования{% endblock %}


{% block  breadcrumbs %}
    <h1>Популярное фото и видео</h1>
{% endblock %}