sclubs/accounts/urls.py
__author__ = 'Evgeniy Tatarintsev'
# -*-coding: utf-8-*-
from django.conf.urls import patterns, url, include
from django.views.generic import DetailView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import logout
from .views import UserProfileView
from .models import User


user_related_urls = patterns('',
    url(r'^$', UserProfileView.as_view(template_name='accounts/profile.html'), name='profile'),
    url(r'^clubs/$', UserProfileView.as_view(template_name='accounts/club_list.html'), name='clubs'),
)

urlpatterns = patterns('',
    #url(r'^login/$', LoginView.as_view(), name='login'),
    #url(r'^', include('social_auth.urls')),
    url(r'^logout/$', login_required(logout), name='logout'),

    url(r'^(?P<pk>\d+)/', include(user_related_urls)),


    ##url(r'^(?P<pk>\d+)/events/$', login_required(UserDetailView.as_view(model=User, template_name='accounts/event_list.html')), name='events'),
    #url(r'^(?P<pk>\d+)/news/$', login_required(UserDetailView.as_view(model=User, template_name='accounts/news_list.html')), name='news'),
    #url(r'^(?P<pk>\d+)/settings/$', login_required(SettingsView.as_view()), name='settings'),

    #url(r'^(?P<pk>\d+)/mail/$', login_required(UserDetailView.as_view(model=User, template_name='accounts/mail.html')), name='mail'),

)

sclubs/clubs/urls.py
__author__ = 'Evgeniy Tatarintsev'
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
from .views import (ClubDetailView,
                    ClubsIndexView,
                    ClubsBySportView,
                    ClubCoachesView,
                    CreateClubView)

urlpatterns = patterns('',
    url(r'^$', ClubsIndexView.as_view(), name='index'),
    url(r'^create/$', login_required(CreateClubView.as_view()), name='create'),
    #url(r'^category/(?P<slug>[-a-zA-Z0-9_]+)/$', CategoryDetailView.as_view(), name='category'),
    url(r'^sport/(?P<slug>[-a-zA-Z0-9_]+)/$', ClubsBySportView.as_view(), name='sport'),
    url(r'^(?P<slug>[-a-zA-Z0-9_]+)/$', ClubDetailView.as_view(), name='detail'),
    url(r'^(?P<slug>[-a-zA-Z0-9_]+)/coaches/$', ClubCoachesView.as_view(), name='coaches'),
)

sclubs/news/urls.py
__author__ = 'Evgeniy Tatarintsev'
from django.conf.urls import patterns, url

from .views import EntryListView, EntryDetail

urlpatterns = patterns('',
    url(r'^$', EntryListView.as_view(), name='index'),
    url(r'^(?P<slug>[-a-zA-Z0-9_]+)/$', EntryDetail.as_view(), name='detail'),
)

sclubs/urls.py
__author__ = 'Evgeniy Tatarintsev'
from django.conf.urls import patterns, url, include
from django.contrib import admin
from django.conf import settings

from sclubs.generic.views import HomePageView

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^ckeditor/', include('ckeditor.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^hit/update/$', 'hitcount.views.update_hit_count_ajax',
                                            name='hitcount_update_ajax'),

    url(r'^$', HomePageView.as_view(), name='home-page'),
    url(r'^news/', include('sclubs.news.urls', namespace='news')),
    url(r'^articles/', include('sclubs.articles.urls', namespace='articles')),
    url(r'^clubs/', include('sclubs.clubs.urls', namespace='clubs')),
    url(r'^accounts/', include('sclubs.accounts.urls', namespace='accounts')),

)


if settings.DEBUG:
    urlpatterns += patterns("",
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
            'show_indexes': True}),
    )

sclubs/utils/urls.py
__author__ = 'Evgeniy Tatarintsev'
import re
import unicodedata

from django.core.exceptions import ObjectDoesNotExist
from django.core.urlresolvers import (resolve, reverse, NoReverseMatch,
                                      get_script_prefix)
from django.shortcuts import redirect
from django.utils.encoding import smart_unicode
from django.utils import translation

from sclubs import settings
from sclubs.utils.importing import import_dotted_path


def admin_url(model, url, object_id=None):
    """
    Returns the URL for the given model and admin url name.
    """
    opts = model._meta
    url = "admin:%s_%s_%s" % (opts.app_label, opts.object_name.lower(), url)
    args = ()
    if object_id is not None:
        args = (object_id,)
    return reverse(url, args=args)


def home_slug():
    """
    Returns the slug arg defined for the ``home`` urlpattern, which
    is the definitive source of the ``url`` field defined for an
    editable homepage object.
    """
    prefix = get_script_prefix()
    slug = reverse("home")
    if slug.startswith(prefix):
        slug = '/' + slug[len(prefix):]
    try:
        return resolve(slug).kwargs["slug"]
    except KeyError:
        return slug




def unique_slug(queryset, slug_field, slug):
    """
    Ensures a slug is unique for the given queryset, appending
    an integer to its end until the slug is unique.
    """
    i = 0
    while True:
        if i > 0:
            if i > 1:
                slug = slug.rsplit("-", 1)[0]
            slug = "%s-%s" % (slug, i)
        try:
            queryset.get(**{slug_field: slug})
        except ObjectDoesNotExist:
            break
        i += 1
    return slug


def login_redirect(request):
    """
    Returns the redirect response for login/signup. Favors:
    - next param
    - LOGIN_REDIRECT_URL setting
    - homepage
    """
    ignorable_nexts = ("",)
    if "sclubs.accounts" in settings.INSTALLED_APPS:
        from sclubs.accounts import urls
        ignorable_nexts += (urls.SIGNUP_URL, urls.LOGIN_URL, urls.LOGOUT_URL)
    next = request.REQUEST.get("next", "")
    if next in ignorable_nexts:
        try:
            next = reverse(settings.LOGIN_REDIRECT_URL)
        except NoReverseMatch:
            next = "/"
    return redirect(next)


def path_to_slug(path):
    """
    Removes everything from the given URL path, including
    language code and ``PAGES_SLUG`` if any is set, returning
    a slug that would match a ``Page`` instance's slug.
    """
    from mezzanine.urls import PAGES_SLUG
    lang_code = translation.get_language_from_path(path)
    for prefix in (lang_code, settings.SITE_PREFIX, PAGES_SLUG):
        if prefix:
            path = path.replace(prefix, "", 1)
    return path.strip("/") or "/"

sclubs/accounts/models.py
__author__ = 'Evgeniy Tatarintsev'
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.utils.http import urlquote
from django.utils import timezone

from sclubs.settings.conf import DEFAULT_USER_ID_LENGTH, USER_ID_PREFIX
from .managers import UserManager


def gen_user_id(pk):
    """
    Generate verbose user id
    """
    blank_space = DEFAULT_USER_ID_LENGTH - len(USER_ID_PREFIX) - len(str(pk))
    return USER_ID_PREFIX + \
           ''.join(['0' for i in range(blank_space)]) + \
           str(pk)


class User(AbstractBaseUser, PermissionsMixin):
    """
    User object for sclubs project
    use email as username
    """
    email = models.EmailField(_('email address'), unique=True, db_index=True,
                              null=True, blank=True)
    slug = models.SlugField(_('Verbose user ID'), max_length=50, unique=True)
    is_active = models.BooleanField(_('active'), default=True,
        help_text=_('Designates whether this user should be treated as '
                    'active. Unselect this instead of deleting accounts.'))
    is_staff = models.BooleanField(_('staff status'), default=False,
        help_text=_('Designates whether the user can log into this admin '
                    'site.'))
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)



    USERNAME_FIELD = 'email'
    objects = UserManager()

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def save(self, *args, **kwargs):
        super(User, self).save(*args, **kwargs)

        if not self.slug:
            self.slug = gen_user_id(self.pk)
            self.save(update_fields=['slug', ])

    def email_user(self, subject, message, from_email=None):
        """
        Sends an email to this User.
        Email is sent asynchronously
        """
        raise NotImplementedError

    def get_absolute_url(self):
        return "/users/%s/" % urlquote(self.username)

    def get_full_name(self):
        """
        Returns the first_name plus the last_name, with a space in between.
        """
        return self.email

    def get_short_name(self):
        "Returns the short name for the user."
        return self.email

sclubs/clubs/models.py
#-*- coding: utf-8 -*-
__author__ = 'Evgeniy Tatarintsev'
import os.path
import uuid
from postmarkup import render_bbcode
from django.utils.translation import ugettext, ugettext_lazy as _
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth import get_user_model

from sclubs.core.models import Displayable
from sclubs.generic.models import Sport
from sclubs.core.fields import RichTextField


def upload_to_club(instance, filename):
    ext = filename.split('.')[-1]
    filename = '%s.%s'%(uuid.uuid4(), ext)
    return os.path.join('clubs', instance.slug, filename)


def upload_to_album(instance, filename):
    ext = filename.split('.')[-1]
    filename = '%s.%s'%(uuid.uuid4(), ext)
    return os.path.join('clubs', instance.album.club.slug, 'albums', instance.album.slug, filename)


class Coach(models.Model):
    name = models.CharField(_('Name'), max_length=80)
    user = models.ForeignKey(get_user_model(), verbose_name=_('User'), related_name='+', null=True, blank=True)
    club = models.ForeignKey('Club', verbose_name=_('Club'), related_name='coaches')

    class Meta:
        verbose_name = _('Coach')
        verbose_name_plural = _('Coaches')


class Address(models.Model):
    street = models.CharField(_('Street'), max_length=255)
    phone = models.CharField(_('Phone'), max_length=255)
    club = models.ForeignKey('Club', verbose_name=_('Club'))


class Club(Displayable):
    logo = models.ImageField(_('Logo'), upload_to=upload_to_club)
    sports = models.ManyToManyField(Sport, verbose_name=_('Sports'), related_name='clubs')
    content = RichTextField(_('Content'), config_name='bbcode')
    html_content = RichTextField(_('HTML Content'), blank=True)
    admins = models.ManyToManyField(get_user_model(), verbose_name=_('Admins'), related_name='clubs')

    class Meta:
        verbose_name = _('Club')
        verbose_name_plural = _('Clubs')

    def get_absolute_url(self):
        return reverse('clubs:detail', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        self.html_content = render_bbcode(self.content)
        return super(Club, self).save(*args, **kwargs)


class Album(Displayable):
    club = models.ForeignKey('Club', verbose_name=_('Club'), related_name='albums')

    class Meta:
        verbose_name = _('Album')
        verbose_name_plural = _('Albums')

    def get_absolute_url(self):
        return reverse('clubs:detail', kwargs={'slug': self.slug})


class Image(Displayable):
    image = models.ImageField(_('Image'), upload_to=upload_to_album)
    album = models.ForeignKey(Album, verbose_name=_('Album'), related_name='images')

    class Meta:
        verbose_name = _('Image')
        verbose_name_plural = _('Image')

    def get_absolute_url(self):
        return reverse('clubs:detail', kwargs={'slug': self.slug})

sclubs/exercises/models.py
__author__ = 'Evgeniy Tatarintsev'

sclubs/seo/models.py
__author__ = 'Evgeniy Tatarintsev'
from django.db import models
from django.utils.translation import ugettext as _


class MetaTags(models.Model):
    name = models.CharField(_('Verbose name'), max_length=250)
    page_url = models.CharField(_('Page URL'), max_length=250, db_index=True)

    title = models.CharField(_('Page title'), max_length=100)
    description = models.TextField(_('Page description'))
    keywords = models.CharField(_('Page keywords'), max_length=100, blank=True, null=True)

    class Meta:
        verbose_name = _('Meta tags')
        verbose_name_plural = _('Meta tags')

    def __unicode__(self):
        return self.name

sclubs/clubs/forms.py
#-*- coding: utf-8 -*-
__author__ = 'Evgeniy Tatarintsev'
from django import forms

from .models import Club


class ClubForm(forms.ModelForm):
    class Meta:
        model = Club
        fields = ('title', 'logo', 'content', 'sports')

sclubs/accounts/views.py
#-*- coding: utf-8 -*-
__author__ = 'Evgeniy Tatarintsev'
from django.views.generic import DetailView

from .models import User


class UserProfileView(DetailView):
    context_object_name = "profile_owner"

    def get_queryset(self):
        return User.objects.active()

    def get_context_data(self, **kwargs):
        ctx = super(UserProfileView, self).get_context_data(**kwargs)
        ctx['can_edit'] = self.request.user == self.object
        return ctx

sclubs/articles/views.py
__author__ = 'Evgeniy Tatarintsev'
from django.utils.timezone import now
from django.views.generic import ListView, DetailView
from django.http import Http404

from models import Article, Aphorism, Category
from sclubs.generic.models import Keyword


class ArticleDetailView(DetailView):
    def get_queryset(self):
        return Article.objects.published()

    def get_object(self, queryset=None):
        article = self.get_queryset().filter(slug=self.kwargs['slug'])
        if not article:
            raise Http404
        article.update(last_view=now())
        return article[0]


class CategoryDetailView(DetailView):
    def get_queryset(self):
        return Category.objects.published()


class CategoryListView(ListView):
    def get_queryset(self):
        return Category.objects.published()


class TaggedArticlesView(DetailView):
    model = Keyword
    template_name = 'articles/tagged_list.html'
    context_object_name = 'tag'

sclubs/clubs/views.py
#-*- coding: utf-8 -*-
__author__ = 'Evgeniy Tatarintsev'
from django.views.generic import DetailView, ListView, CreateView, UpdateView
from django.http import Http404
from django.db.models import Q

from sclubs.generic.models import Sport, SportCategory
from .models import Club
from .forms import ClubForm

class ClubsIndexView(ListView):
    def get_queryset(self):
        return Club.objects.published()


class ClubDetailView(DetailView):
    def get_queryset(self):
        return Club.objects.published()


class ClubsBySportView(ListView):
    template_name = 'clubs/clubs_by_sport.html'

    def dispatch(self, request, *args, **kwargs):
        self.sport = None
        self.sport_category = None

        try:
            self.sport = Sport.objects.get(slug=self.kwargs['slug'])
        except Sport.DoesNotExist:
            try:
                self.sport_category = SportCategory.objects.get(slug=self.kwargs['slug'])
            except SportCategory.DoesNotExist:
                raise Http404
        return super(ClubsBySportView, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        if self.sport:
            return Club.objects.published().filter(sports=self.sport)

        return Club.objects.published().filter(sports__categories=self.sport_category).distinct()


class ClubCoachesView(ListView):
    def dispatch(self, request, *args, **kwargs):
        self.club = Club.objects.published().get(slug=kwargs['slug'])
        return super(ClubCoachesView, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        return self.club.coaches.all()

    def get_context_data(self, **kwargs):
        ctx = super(ClubCoachesView, self).get_context_data(**kwargs)
        ctx['club'] = self.club
        return ctx


class CreateClubView(CreateView):
    form_class = ClubForm
    model = Club

sclubs/exercises/views.py
__author__ = 'Evgeniy Tatarintsev'

sclubs/generic/views.py
__author__ = 'Evgeniy Tatarintsev'
from django.views.generic import TemplateView


class HomePageView(TemplateView):
    template_name = 'index.html'

sclubs/news/views.py
__author__ = 'john'
from django.views.generic import ListView, DetailView
from django.conf import settings

from .models import Entry


class EntryListView(ListView):
    paginate_by = getattr(settings, 'NEWS_ON_PAGE', 10)

    def get_queryset(self):
        filters = {}

        if 'sport' in self.request.GET:
            filters['sports__slug'] = self.request.GET['sport']

        return Entry.objects.active(**filters)


class EntryDetail(DetailView):
    def get_queryset(self):
        if 'preview' in self.request.GET and self.request.user.is_staff:
            return Entry.objects.all()

        return Entry.objects.active()

sclubs/templates/accounts/ajax_popup.html
<div class="wrap-opacty">
</div>
<div class="popup-login">
    <h1>Войти или зарегистрироваться</h1>
    {% include "accounts/include_login_form.html" %}
</div>

sclubs/templates/accounts/club_list.html
{% extends "accounts/profile.html" %}

{% load thumbnail %}

{% block meta %}
    <title>{{ profile_owner }}Спортивные клубы </title>
    <meta name="description" content="Спортивные клубы">
    <meta name="keywords" content="Спортивные клубы">
{% endblock %}


{% block  breadcrumbs %}
    <span>Клубы</span>
{% endblock %}


{% block content %}
{% for club in profile_owner.clubs.all %}
    {% include "clubs/club_include.html" %}
{% endfor %}
{% endblock %}

sclubs/templates/accounts/event_list.html
{% extends "accounts/profile.html" %}

{% load tagging_tags thumbnail %}

{% block page_title %}Мои события{% endblock %}
{% block page_description %}Мои события{% endblock %}
{% block page_keywords %}Мои события{% endblock %}


{% block  breadcrumbs %}
    <span>Мои события</span>
{% endblock %}


{% block content %}
{% for event in user.events.all %}
    <div class="wrap-news{% if forloop.last %} list-last{% endif %}">
        <table>
            <tr>
                <td>
                   {% if event.logo %}
                    <div class="td-img">
                        {% thumbnail event.logo "140x100" crop="center" as im %}
                            <img src="{{im.url}}" alt="{{event.title}}">
                        {% endthumbnail %}
                    </div>
                    {% endif %}
                </td>
                <td>
                    <h1><a href="{{ event.get_absolute_url }}">{{ event.title }}</a></h1>
                    <div class="info">
                        <a href="#" class="date">{{ event.date }}</a>
                        <span class="tags tag-info">
                            <a href="{% url "filters:tagged-events" %}?city={{ event.city.id }}">{{event.city}}</a>,
                            <a href="{% url "filters:tagged-events" %}?{{ event.sport.tag.id }}=on">{{event.sport.tag}}</a>
                        </span>
                        
                    </div>
                    <div class="text-news">
                        {{ event.city }}, {{ event.address }}
                    </div>
                </td>
            </tr>
        </table>
    </div>
{% endfor %}
{% endblock %}

sclubs/templates/accounts/include_login_form.html
{% load widget_tweaks %}

<div class="login-wrap">
    <table>
        <tr>
            <td>
                <form class="login-form" action="{% url "accounts:login" %}?next={{ request.GET.next }}" method="POST"> {% csrf_token %}
                <table>
                    <tr>
                        <td>{{ form.email|append_attr:"placeholder:E-mail"|add_class:"field-form"|add_error_class:"errordata" }}</td>
                    </tr>
                    <tr>
                        <td>{{ form.password|append_attr:"placeholder:Пароль"|add_class:"field-form"|add_error_class:"errordata" }}</td>
                    </tr>
                    <tr>
                        <td>{{ form.register|append_attr:"id:no-register"|add_error_class:"errordata" }}
                            <label for="no-register">
                                {% comment %}
                                <span>
                                    <img src="{{STATIC_URL}}img/checked.png">
                                </span>  
                                {% endcomment %}                            
                                Я ещё не зарегистрирован
                            </label>
                        </td>
                    </tr>
                    <tr id="tr-captcha">
                        <td>{{ form.captcha|add_class:"field-form"|add_error_class:"errordata" }}</td>
                    </tr>
                    {% if form.non_field_errors %}
                    <tr>
                        <td><span class="error-form">{{form.non_field_errors.0|safe}}</span></td>
                    </tr>
                    {% endif %}
                    <tr>
                        <td><button type="submit" id="login-button">Войти</button></td>
                    </tr>
                </table>
                    <input type="hidden" name="next" value="{{ request.GET.next }}">
                </form>
            </td>
            <td>
                <a class="soc-auth" id="vk-auth" href="{% url 'accounts:socialauth_begin' 'vk-oauth' %}?next={{ request.GET.next }}"><img src="{{STATIC_URL}}img/vk.png" alt=""></a>
                <a class="soc-auth" id="fb-auth" href="{% url 'accounts:socialauth_begin' 'facebook' %}?next={{ request.GET.next }}"><img src="{{STATIC_URL}}img/fb.png" alt=""></a>
                <a class="soc-auth" id="ya-auth" href="{% url 'accounts:socialauth_begin' 'yandex' %}?next={{ request.GET.next }}"><img src="{{STATIC_URL}}img/ya.png" alt=""></a>
                <a class="soc-auth" id="tw-auth" href="{% url 'accounts:socialauth_begin' 'twitter' %}?next={{ request.GET.next }}"><img src="{{STATIC_URL}}img/tw.png" alt=""></a>
            </td>
        </tr>
    </table>
</div>

sclubs/templates/accounts/login.html
{% extends "base.html" %}


{% block page_title %}О проекте sclubs.ru{% endblock %}

{% block page_description %}Что такое sclubs.ru цели и досижения проекта.{% endblock %}

{% block page_keywords %}сайт sclubs.ru, что такое sclubs.ru, о проекте sclubs.ru, склабс{% endblock %}

{% block  breadcrumbs %}
    <span>Войти или зарегистрироваться</span>
{% endblock %}

{% block singin %}
    {% if request.user.is_authenticated %}
        <a href="{% url "accounts:profile" pk=request.user.pk %}">{{ request.user.username }}</a>
        <a href="{% url "accounts:logout" %}?next={{ request.get_full_path }}">Выйти</a>
    {% else %}
        <a href="{% url "accounts:login" %}?next={{ request.get_full_path }}">Войти</a>
    {% endif %}
{% endblock %}

{% block content %}
	{% include "accounts/include_login_form.html" %}
{% endblock %}

sclubs/templates/accounts/news_form.html
{% extends "accounts/profile.html" %}

{% load comments tagging_tags thumbnail %}

{% block page_title %}Добавить мою новость{% endblock %}
{% block page_description %}Добавить мою новость{% endblock %}
{% block page_keywords %}Добавить мою новость{% endblock %}


{% block  breadcrumbs %}
    <span>Добавить мою новость</span>
{% endblock %}


{% block content %}

{% endblock %}

sclubs/templates/accounts/news_list.html
{% extends "accounts/profile.html" %}

{% load comments tagging_tags thumbnail %}

{% block page_title %}Мои новости{% endblock %}
{% block page_description %}Мои новости{% endblock %}
{% block page_keywords %}Мои новости{% endblock %}


{% block  breadcrumbs %}
    <span>Мои новости</span>
{% endblock %}


{% block content %}
{% for entry in user.news.all %}
    <div class="wrap-news{% if forloop.last %} list-last{% endif %}">
        <table>
            <tr>
                <td class="col1">
                   {% if entry.image %}
                    <div class="td-img">
                        {% thumbnail entry.image "140x100" crop="center" as im %}
                            <img src="{{im.url}}" alt="{{entry.title}}">
                        {% endthumbnail %}
                    </div>
                    {% endif %}
                </td>
                <td>
                    <h1>{% if entry.published %}<a href="{{ entry.get_absolute_url }}">{{ entry.title }}</a>{% else %}<a href="#">{{ entry.title }}</a>{% endif %}</h1>
                    <div class="info">
                        <a href="#" class="date">{{ entry.date|date:"j E - H:i" }}</a>
                        {% get_comment_count for entry as comment_count %}
                        {% if comment_count %}
                        <a href="{{ entry.get_absolute_url }}#comments" class="comments">{{ comment_count }}</a>
                        {% endif %}
                        <a class="control-edit" href="{% url "news:edit" slug=entry.slug %}">Редактировать</a>
                    </div>
                    <div class="text-news">
                        {{ entry.description }}
                    </div>
                </td>
            </tr>
        </table>
    </div>
{% endfor %}
{% endblock %}

sclubs/templates/accounts/profile.html
{% extends "base.html" %}

{% load thumbnail comments %}

{% block page_title %}Профиль{% endblock %}

{% block page_description %}Профиль{% endblock %}

{% block page_keywords %}Профиль{% endblock %}

{% block  breadcrumbs %}
    <span>Лента</span>
{% endblock %}

{% block content %}

<div class="main-content">
   {% for entry in user_lenta %}
    <div class="wrap-news{% if forloop.last %} list-last{% endif %}">
        <table>
            <tr>
                <td class="col1">
                   {% if entry.image %}
                    <div class="td-img">
                        {% thumbnail entry.image "140x100" crop="center" as im %}
                            <img src="{{im.url}}" alt="{{entry.title}}">
                        {% endthumbnail %}
                    </div>
                    {% endif %}
                </td>
                <td>
                    <h1><a href="{{ entry.get_absolute_url }}">{{ entry.title }}</a></h1>
                    <div class="info">
                        <a href="#" class="date">{{ entry.date|date:"j E - H:i" }}</a>
                        {% get_comment_count for entry as comment_count %}
                        {% if comment_count %}
                        <a href="{{ entry.get_absolute_url }}#comments" class="comments">{{ comment_count }}</a>
                        {% endif %}
                    </div>
                    <div class="text-news">
                        {{ entry.description }}
                    </div>
                </td>
            </tr>
        </table>
    </div>
{% endfor %}

</div>
{% endblock %}


{% block navigation %}
<div class="navigation">

    <div class="head-nav article-head-nav">
        Меню пользователя
    </div>

    {% include "accounts/user_menu.html" %}

</div>
{% endblock %}

sclubs/templates/accounts/user_menu.html
<div class="content-nav">
    <div class="paddin-content-nav">
        <div class="wrap-content-nav">
            <table>
                <tr>
                    <td class="img-nav">
                    </td>
                    <td>
                        <div class="text-nav">
                            {% if can_edit %}
                            <a class="add-item-nav" href="{% url "clubs:create" %}">Добавить</a>
                            {% endif %}
                            <a href="{% url "accounts:clubs" pk=profile_owner.pk %}">Клубы</a>
                        </div>
                    </td>
                </tr>
            </table>
        </div>
    </div>

    <div class="paddin-content-nav">
        <div class="wrap-content-nav">
            <table>
                <tr>
                    <td class="img-nav">
                    </td>
                    <td>
                        <div class="text-nav">
                            <a class="add-item-nav" href="{#% url "events:event-create" %#}">Добавить</a>
                            <a href="{#% url "accounts:events" pk=user.pk %#}">Мои события</a>
                        </div>
                    </td>
                </tr>
            </table>
        </div>
    </div>

    <div class="paddin-content-nav">
        <div class="wrap-content-nav">
            <table>
                <tr>
                    <td class="img-nav">
                    </td>
                    <td>
                        <div class="text-nav">
                            <a class="add-item-nav" href="{#% url "news:create" %#}">Добавить</a>
                            <a href="{#% url "accounts:news" pk=user.pk %#}">Мои новости</a>
                        </div>
                    </td>
                </tr>
            </table>
        </div>
    </div>

    <div class="paddin-content-nav">
        <div class="wrap-content-nav list-last">
            <table>
                <tr>
                    <td class="img-nav">
                    </td>
                    <td>
                        <div class="text-nav">
                            <a href="{#% url "accounts:settings" pk=user.pk %#}">Мои настройки</a>
                        </div>
                    </td>
                </tr>
            </table>
        </div>
    </div>
    {% comment %}
    <div class="paddin-content-nav">
        <div class="wrap-content-nav list-last">
            <table>
                <tr>
                    <td class="img-nav">
                    </td>
                    <td>
                        <div class="text-nav">
                            <a href="{% url "accounts:mail" pk=user.pk %}">Личные сообщения <strong>(1)</strong></a>
                        </div>
                    </td>
                </tr>
            </table>
        </div>
    </div>
    {% endcomment %}


</div>